### ISSUE TITLE
Transaction does not return the expected Failure

### ISSUE THREAD

**Issue by wuarmin** [dry-rb/dry-operation#23]
Hey :wave: ,

please checkout this spec. I expect that the code rolls back and returns the `Failure(:failure)`, but instead it returns `Success(nil)`. 
Am i misunderstanding something, or is this wrong behavior? If yes, what's the correct way to return the `Failure`.

```ruby
require "spec_helper"
require "dry/operation"

RSpec.describe Dry::Operation::Extensions::ROM do
  include Dry::Monads[:result]

  let(:rom) do
    ROM.container(:sql, "sqlite:memory") do |config|
      config.default.create_table(:foo) do
        column :bar, :string
      end

      config.relation(:foo)
    end
  end

  let(:base) do
    Class.new(Dry::Operation) do
      include Dry::Operation::Extensions::ROM

      attr_reader :rom

      def initialize(rom:)
        @rom = rom
        super()
      end
    end
  end

  it "should roll back and return the failure" do
    instance = Class.new(base) do
      def call
        transaction do
          step create_record
          step failure
        end
      end

      def create_record
        Success(rom.relations[:foo].command(:create).call(bar: "bar"))
      end

      def failure
        Failure(:failure)
      end
    end.new(rom: rom)

    result = instance.call

    expect(result).to be_failure
  end
end
```
Thanks!

**Comment by waiting-for-dev** [comment]
Hmm, no, that doesn't look as something expected :/

**Comment by wuarmin** [comment]
Hey @waiting-for-dev,
WDYT? What's the right way to fix this?

thanks

**Comment by waiting-for-dev** [comment]
Hey @wuarmin, thanks for the nudge. I'm buried in work these days but this is my number one priority beyond that, so I'll be able to take a look very soon 🙂

**Comment by tylerhunt** [comment]
Here's a working monkey-patch if anyone needs it in the meantime: https://gist.github.com/tylerhunt/4e4248ff350028fbce6dbb068dd588b1

**Comment by waiting-for-dev** [comment]
A fix is available at https://github.com/dry-rb/dry-operation/pull/25 Thanks for your patience with this one, folks! 🙏

**Comment by wuarmin** [comment]
@waiting-for-dev thanks for the great work!
